spring:
  application:
    name: artist-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0
  